;; -*- mode: eask; lexical-binding: t -*-

(package "b"
         "0.0.1"
         "Utility functions for buffer manipulation")

(website-url "https://github.com/emacs-php/b.el")
(keywords "lisp" "buffer")

(package-file "b.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
